# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`Types-XSD-Lite`
	:runtime-requirement  [ :on "Type::Library 0.004"^^:CpanId ];
	:test-requirement     [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement     [ :on "Test::TypeTiny 0.004"^^:CpanId ];
	:test-requirement     [ :on "Test::Requires"^^:CpanId ];
	:test-requirement     [ :on "Test::Fatal"^^:CpanId ];
	:test-recommendation  [ :on "Moo 1.003000"^^:CpanId ].
